
import { SlotStatus } from '../models';

let slots = [];

// Field Team Data from CSV (64 teams)
let teams = [
    { teamNumber: '10-B', teamLeader: 'Jacob Allen', phone: '0499 943 615', email: 'jacob.allen@dpi.qld.gov.au', altLeader: 'Mark (Mariusz) Chmiel', altPhone: '0436 668 953', altEmail: 'mark.chmiel@dpi.qld.gov.au', area: 'Jarred', areaCoordinator: 'Michelle', areaCoordinatorEmail: 'michelle@dpi.qld.gov.au', type: 'K9', depotLocation: 'Berrinba/Wacol', status: 'active', battery: 85 },
    { teamNumber: '49', teamLeader: 'Vacant', phone: '0499 327 626', email: 'Vacant', altLeader: '', altPhone: 'Vacant', altEmail: '', area: '0436 660 888', areaCoordinator: 'Sean Melton', areaCoordinatorEmail: 'sean.melton@dpi.qld.gov.au', type: '', depotLocation: 'Caboolture', status: 'active', battery: 70 },
    { teamNumber: '33', teamLeader: 'Beau', phone: '0458 632 823', email: 'beau.garrett@dpi.qld.gov.au', altLeader: 'Thomas Ryan', altPhone: '0499 752 537', altEmail: 'thomas.ryan@dpi.qld.gov.au', area: 'Jade Dean', areaCoordinator: 'Jade Dean', areaCoordinatorEmail: 'jade.dean@dpi.qld.gov.au', type: '', depotLocation: 'Gold Coast', status: 'active', battery: 90 },
    { teamNumber: '22', teamLeader: 'Dekoda Chisholm', phone: '0439 564 810', email: 'dekoda.chisholm@dpi.qld.gov.au', altLeader: 'Bryan Hodges', altPhone: '0447 206 685', altEmail: 'bryan.hodges@dpi.qld.gov.au', area: 'Matt Courtney; Roanne Camilleri', areaCoordinator: 'Matt Courtney; Roanne Camilleri', areaCoordinatorEmail: 'matthew.courtney@dpi.qld.gov.au; roanne.camilleri@dpi.qld.gov.au', type: '', depotLocation: 'Mutdapilly', status: 'active', battery: 75 },
    { teamNumber: '18', teamLeader: 'Jon Jonovski', phone: '0419 316 841', email: 'jon.jonovski@dpi.qld.gov.au', altLeader: 'Rohan Horne', altPhone: 'TBA', altEmail: 'rohan.horne@dpi.qld.gov.au', area: 'Jamie', areaCoordinator: 'Chris Acworth', areaCoordinatorEmail: 'chris.acworth@dpi.qld.gov.au', type: '', depotLocation: 'Berrinba/Wacol', status: 'active', battery: 80 },
    { teamNumber: '50', teamLeader: 'Rory Bailey', phone: '0407 799 440', email: 'rory.bailey@dpi.qld.gov.au', altLeader: 'Daniel Pearman', altPhone: '0475 954 715', altEmail: 'daniel.pearman@dpi.qld.gov.au', area: 'Sean Melton', areaCoordinator: 'Sean Melton', areaCoordinatorEmail: 'Sean.Melton@dpi.qld.gov.au', type: '', depotLocation: 'Caboolture', status: 'active', battery: 65 },
    { teamNumber: 'FAST-5', teamLeader: 'Cody Story', phone: '0457318 277', email: 'cody.story@dpi.qld.gov.au', altLeader: '', altPhone: '', altEmail: '', area: 'Fast Aerial', areaCoordinator: 'William Taylor', areaCoordinatorEmail: 'william.taylor@dpi.qld.gov.au', type: 'Fast Aerial', depotLocation: 'Fast Aerial Operations', status: 'active', battery: 95 },
    { teamNumber: '2', teamLeader: 'Micheal Graham', phone: '0448 567 216', email: 'mick.graham@dpi.qld.gov.au', altLeader: 'PJ Brady', altPhone: '0459 864 300', altEmail: 'pj.brady@dpi.qld.gov.au', area: 'David Elliott; Roanne Camelleri', areaCoordinator: 'David Elliott; Roanne Camelleri', areaCoordinatorEmail: 'David.Elliott@dpi.qld.gov.au; Roanne.Camilleri@dpi.qld.gov.au', type: '', depotLocation: 'Various', status: 'active', battery: 88 },
    { teamNumber: 'FAST-6', teamLeader: 'Corey Doran', phone: '0456 811 598', email: 'corey.doran@dpi.qld.gov.au', altLeader: '', altPhone: '', altEmail: '', area: 'Fast Aerial', areaCoordinator: 'William Taylor', areaCoordinatorEmail: 'william.taylor@dpi.qld.gov.au', type: 'Fast Aerial', depotLocation: 'Fast Aerial Operations', status: 'active', battery: 92 },
    { teamNumber: '13', teamLeader: 'Rohan Lawrance', phone: '0482 835 461', email: 'rohan.lawrance@dpi.qld.gov.au', altLeader: 'Melissa Gibson', altPhone: '0438 162 064', altEmail: 'melissa.gibson@dpi.qld.gov.au', area: 'Matt Courtney; Roanne Camilleri', areaCoordinator: 'Matt Courtney; Roanne Camilleri', areaCoordinatorEmail: 'matthew.courtney@dpi.qld.gov.au; roanne.camilleri@dpi.qld.gov.au', type: '', depotLocation: 'Mutdapilly', status: 'active', battery: 78 },
    { teamNumber: '54', teamLeader: 'Alicia Allan', phone: '0408 544 189', email: 'alicia.allan@dpi.qld.gov.au', altLeader: 'Sinh Chao', altPhone: '0460 015 244', altEmail: 'sinh.chao@dpi.qld.gov.au', area: 'Sean Melton', areaCoordinator: 'Sean Melton', areaCoordinatorEmail: 'sean.melton@dpi.qld.gov.au', type: '', depotLocation: 'Caboolture', status: 'active', battery: 72 },
    { teamNumber: 'AERIAL-1', teamLeader: 'Dave Gonzalez', phone: '0436 917 246', email: 'dave.gonzalez@dpi.qld.gov.au', altLeader: '', altPhone: '', altEmail: '', area: 'Aerial', areaCoordinator: 'Mikhala Barford', areaCoordinatorEmail: 'mikhala.barford@dpi.qld.gov.au', type: 'Aerial', depotLocation: 'Aerial Operations', status: 'charging', battery: 15 },
    { teamNumber: '8', teamLeader: 'Mariah Camilleri', phone: '0473 234 212', email: 'mariah.camilleri@dpi.qld.gov.au', altLeader: 'Andrew Rea', altPhone: '0474 061 670', altEmail: 'andrew.rea@dpi.qld.gov.au', area: 'David Elliott; Roanne Camelleri', areaCoordinator: 'David Elliott; Roanne Camelleri', areaCoordinatorEmail: 'David.Elliott@dpi.qld.gov.au; Roanne.Camilleri@dpi.qld.gov.au', type: '', depotLocation: 'Various', status: 'active', battery: 83 },
    { teamNumber: '48', teamLeader: 'Regan Mcmanaway', phone: '0448 420 524', email: 'regan.mcmanaway@dpi.qld.gov.au', altLeader: 'Tony MacKinnon', altPhone: '0436 926 565', altEmail: 'tony.mackinnon@dpi.qld.gov.au', area: 'Andrew (Drew) Wratt', areaCoordinator: 'Andrew (Drew) Wratt', areaCoordinatorEmail: 'andrew.wratt@dpi.qld.gov.au', type: '', depotLocation: 'Caboolture', status: 'active', battery: 68 },
    { teamNumber: 'FAST-2', teamLeader: 'Greg McKinlay', phone: '0459 024 387', email: 'greg.mckinlay@dpi.qld.gov.au', altLeader: '', altPhone: '', altEmail: '', area: 'Fast Aerial', areaCoordinator: 'William Taylor', areaCoordinatorEmail: 'william.taylor@dpi.qld.gov.au', type: 'Fast Aerial', depotLocation: 'Fast Aerial Operations', status: 'active', battery: 91 },
    { teamNumber: '1', teamLeader: 'Michael Rhodes', phone: '0461 329 849', email: 'michael.rhodes@dpi.qld.gov.au', altLeader: 'Brian Paenga', altPhone: '0459 467 678', altEmail: 'brian.paenga@dpi.qld.gov.au', area: 'Jade Dean', areaCoordinator: 'Jade Dean', areaCoordinatorEmail: 'jade.dean@dpi.qld.gov.auuu', type: '', depotLocation: 'Gold Coast', status: 'active', battery: 87 },
    { teamNumber: '31', teamLeader: 'Emma Sutton', phone: '0461 320 223', email: 'emma.sutton@dpi.qld.gov.au', altLeader: 'Jordan Bailey', altPhone: '0497 324 021', altEmail: 'jordan.bailey@dpi.qld.gov.au', area: 'Sam MacFarlane', areaCoordinator: 'Sam MacFarlane', areaCoordinatorEmail: 'sam.macfarlane@dpi.qld.gov.au', type: '', depotLocation: 'Gold Coast', status: 'active', battery: 76 },
    { teamNumber: 'AERIAL-3', teamLeader: 'Matthew Noris', phone: '0488 559 671', email: 'matthew.noris@dpi.qld.gov.au', altLeader: '', altPhone: '', altEmail: '', area: 'Aerial', areaCoordinator: 'Mikhala Barford', areaCoordinatorEmail: 'mikhala.barford@dpi.qld.gov.au', type: 'Aerial', depotLocation: 'Aerial Operations', status: 'active', battery: 89 },
    { teamNumber: '60', teamLeader: 'Skye Courts', phone: '0460 022 948', email: 'skye.courts@dpi.qld.gov.au', altLeader: 'Arran Robertson', altPhone: '0448 360 349', altEmail: 'arran.robertson@dpi.qld.gov.au', area: 'Tanille Rachinger', areaCoordinator: 'Tanille Rachinger', areaCoordinatorEmail: 'tanille.rachinger@dpi.qld.gov.au', type: '', depotLocation: 'Gold Coast', status: 'active', battery: 85 },
    { teamNumber: '61', teamLeader: 'Karl Begon', phone: '0459 467 678', email: 'karl.begon@dpi.qld.gov.au', altLeader: 'Cory Taylor', altPhone: '0468 452 012', altEmail: 'cory.taylor@dpi.qld.gov.au', area: 'Jade Dean', areaCoordinator: 'Jade Dean', areaCoordinatorEmail: 'Jade.Dean@dpi.qld.gov.au', type: '', depotLocation: 'Gold Coast', status: 'active', battery: 79 },
    { teamNumber: '41', teamLeader: 'Nathan Reid', phone: '0474 066 803', email: 'nathan.reid@dpi.qld.gov.au', altLeader: 'Sally Shalders', altPhone: '0499 943 621', altEmail: 'sally.shalders@dpi.qld.gov.au', area: 'Carolina Hengler', areaCoordinator: 'Carolina Hengler', areaCoordinatorEmail: 'carolina.hengler@dpi.qld.gov.au', type: '', depotLocation: 'Caboolture', status: 'active', battery: 74 },
    { teamNumber: '16', teamLeader: 'Andrew Boyce', phone: '0457 091 886', email: 'andrew.boyce@dpi.qld.gov.au', altLeader: 'Andrew Woodward', altPhone: '0407 783 419', altEmail: 'andrew.woodward@dpi.qld.gov.au', area: 'Sam MacFarlane', areaCoordinator: 'Sam MacFarlane', areaCoordinatorEmail: 'sam.macfarlane@dpi.qld.gov.au', type: '', depotLocation: 'Gold Coast', status: 'active', battery: 82 },
    { teamNumber: '30', teamLeader: 'Cody Warne', phone: '0409 883 316', email: 'cody.warne@dpi.qld.gov.au', altLeader: 'Sam Allen', altPhone: '0499 752 541', altEmail: 'sam.allen@dpi.qld.gov.au', area: 'Tanille Rachinger', areaCoordinator: 'Tanille Rachinger', areaCoordinatorEmail: 'tanille.rachinger@dpi.qld.gov.au', type: '', depotLocation: 'Gold Coast', status: 'active', battery: 77 },
    { teamNumber: 'FAST-3', teamLeader: 'Damian McMahon', phone: '0409 863 314', email: 'damian.mcmahon@dpi.qld.gov.au', altLeader: '', altPhone: '', altEmail: '', area: 'Fast Aerial', areaCoordinator: 'William Taylor', areaCoordinatorEmail: 'william.taylor@dpi.qld.gov.au', type: 'Fast Aerial', depotLocation: 'Fast Aerial Operations', status: 'active', battery: 93 },
    { teamNumber: '59', teamLeader: 'Greg Andrews', phone: '0408 712 646', email: 'greg.andrews@dpi.qld.gov.au', altLeader: 'Doug Blackburn', altPhone: '0436 660 886', altEmail: 'doug.blackburn@dpi.qld.gov.au', area: 'Tanille Rachinger', areaCoordinator: 'Tanille Rachinger', areaCoordinatorEmail: 'tanille.rachinger@dpi.qld.gov.au', type: '', depotLocation: 'Gold Coast', status: 'active', battery: 71 },
    { teamNumber: 'FAST-4', teamLeader: 'Ricky Reid', phone: '0457 050 781', email: 'ricky.reid@dpi.qld.gov.au', altLeader: '', altPhone: '', altEmail: '', area: 'Fast Aerial', areaCoordinator: 'William Taylor', areaCoordinatorEmail: 'william.taylor@dpi.qld.gov.au', type: 'Fast Aerial', depotLocation: 'Fast Aerial Operations', status: 'active', battery: 94 },
    { teamNumber: '28', teamLeader: 'Harry Atfield', phone: '0436 680 813', email: 'harry.atfield@dpi.qld.gov.au', altLeader: 'Sian Thomas', altPhone: '0408 430 341', altEmail: 'sian.thomas@dpi.qld.gov.au', area: 'Tanille Rachinger', areaCoordinator: 'Tanille Rachinger', areaCoordinatorEmail: 'tanille.rachinger@dpi.qld.gov.au', type: '', depotLocation: 'Gold Coast', status: 'active', battery: 81 },
    { teamNumber: '46', teamLeader: 'Jessica Costelloe', phone: '0488 451 291', email: 'jessica.costelloe@dpi.qld.gov.au', altLeader: 'Doug Young', altPhone: '0401 545 885', altEmail: 'doug.young@dpi.qld.gov.au', area: 'Andrew (Drew) Wratt', areaCoordinator: 'Andrew (Drew) Wratt', areaCoordinatorEmail: 'andrew.wratt@dpi.qld.gov.au', type: '', depotLocation: 'Caboolture', status: 'active', battery: 69 },
    { teamNumber: '6', teamLeader: 'Lachlan Wood', phone: '0499 752 514', email: 'lachlan.wood@dpi.qld.gov.au', altLeader: 'Kim White', altPhone: '0436 668 949', altEmail: 'kim.white@dpi.qld.gov.au', area: 'Jamie', areaCoordinator: 'Chris Acworth', areaCoordinatorEmail: 'chris.acworth@dpi.qld.gov.au', type: '', depotLocation: 'Berrinba/Wacol', status: 'active', battery: 86 },
    { teamNumber: 'FAST-1', teamLeader: 'Rohan Hall', phone: '0457 326 849', email: 'rohan.hall@dpi.qld.gov.au', altLeader: '', altPhone: '', altEmail: '', area: 'Fast Aerial', areaCoordinator: 'William Taylor', areaCoordinatorEmail: 'william.taylor@dpi.qld.gov.au', type: 'Fast Aerial', depotLocation: 'Fast Aerial Operations', status: 'active', battery: 96 },
    { teamNumber: '62', teamLeader: 'Alec Beattie', phone: '0436 926 576', email: 'alec.beattie@dpi.qld.gov.au', altLeader: 'Greg Jackson', altPhone: '0436 668 952', altEmail: 'greg.jackson@dpi.qld.gov.au', area: 'Tanille Rachinger', areaCoordinator: 'Tanille Rachinger', areaCoordinatorEmail: 'tanille.rachinger@dpi.qld.gov.au', type: '', depotLocation: 'Gold Coast', status: 'active', battery: 73 },
    { teamNumber: '4', teamLeader: 'Craig Robb', phone: '0459 864 303', email: 'craig.robb@dpi.qld.gov.au', altLeader: 'Barry MacDonald', altPhone: '0447 751 033', altEmail: 'barry.mcdonald@dpi.qld.gov.au', area: 'David Elliott; Roanne Camelleri', areaCoordinator: 'David Elliott; Roanne Camelleri', areaCoordinatorEmail: 'David.Elliott@dpi.qld.gov.au; Roanne.Camilleri@dpi.qld.gov.au', type: '', depotLocation: 'Various', status: 'active', battery: 84 },
    { teamNumber: '12', teamLeader: 'Drew Delaney', phone: '0491 381 562', email: 'drew.delaney@dpi.qld.gov.au', altLeader: 'Jack McDonald', altPhone: '0499 943 624', altEmail: 'jack.mcdonald@dpi.qld.gov.au', area: 'Matt Courtney; Roanne Camilleri', areaCoordinator: 'Matt Courtney; Roanne Camilleri', areaCoordinatorEmail: 'matthew.courtney@dpi.qld.gov.au; roanne.camilleri@dpi.qld.gov.au', type: '', depotLocation: 'Mutdapilly', status: 'busy', battery: 60 },
    { teamNumber: '44', teamLeader: 'Hannah Bailey', phone: '0408 633 854', email: 'hannah.bailey@dpi.qld.gov.au', altLeader: 'Anthony Donovan', altPhone: '0499 327 661', altEmail: 'anthony.donovan@dpi.qld.gov.au', area: 'Carolina Hengler', areaCoordinator: 'Carolina Hengler', areaCoordinatorEmail: 'carolina.hengler@dpi.qld.gov.au', type: '', depotLocation: 'Caboolture', status: 'active', battery: 75 },
    { teamNumber: 'AERIAL-2', teamLeader: 'Daniel Sallaway', phone: '0474 806 664', email: 'daniel.sallaway@dpi.qld.gov.au', altLeader: '', altPhone: '', altEmail: '', area: 'Aerial', areaCoordinator: 'Mikhala Barford', areaCoordinatorEmail: 'mikhala.barford@dpi.qld.gov.au', type: 'Aerial', depotLocation: 'Aerial Operations', status: 'active', battery: 88 },
    { teamNumber: '3', teamLeader: 'Nathan McDonald', phone: '0499 752 534', email: 'nathan.mcdonald@dpi.qld.gov.au', altLeader: 'Mick Ryan', altPhone: '0499 752 526', altEmail: 'mick.ryan@dpi.qld.gov.au', area: 'David Elliott; Roanne Camelleri', areaCoordinator: 'David Elliott; Roanne Camelleri', areaCoordinatorEmail: 'David.Elliott@dpi.qld.gov.au; Roanne.Camilleri@dpi.qld.gov.au', type: '', depotLocation: 'Various', status: 'active', battery: 82 },
    { teamNumber: '11', teamLeader: 'Ben Noonan', phone: '0429 989 857', email: 'ben.noonan@dpi.qld.gov.au', altLeader: 'Steve Boettcher', altPhone: '0448 425 025', altEmail: 'steve.boettcher@dpi.qld.gov.au', area: 'Matt Courtney; Roanne Camilleri', areaCoordinator: 'Matt Courtney; Roanne Camilleri', areaCoordinatorEmail: 'matthew.courtney@dpi.qld.gov.au; roanne.camilleri@dpi.qld.gov.au', type: '', depotLocation: 'Mutdapilly', status: 'active', battery: 78 },
    { teamNumber: '5', teamLeader: 'Rhys Woodley', phone: '0491 389 145', email: 'rhys.woodley@dpi.qld.gov.au', altLeader: 'Kyle Johnston', altPhone: '0499 752 551', altEmail: 'kyle.johnston@dpi.qld.gov.au', area: 'David Elliott; Roanne Camelleri', areaCoordinator: 'David Elliott; Roanne Camelleri', areaCoordinatorEmail: 'David.Elliott@dpi.qld.gov.au; Roanne.Camilleri@dpi.qld.gov.au', type: '', depotLocation: 'Various', status: 'active', battery: 80 },
    { teamNumber: '52', teamLeader: 'Joel van der Poel', phone: '0457 050 796', email: 'joel.van-der-poel@dpi.qld.gov.au', altLeader: 'Simon Collins', altPhone: '0447 206 687', altEmail: 'simon.collins@dpi.qld.gov.au', area: 'Sean Melton', areaCoordinator: 'Sean Melton', areaCoordinatorEmail: 'sean.melton@dpi.qld.gov.au', type: '', depotLocation: 'Caboolture', status: 'active', battery: 67 },
    { teamNumber: '19', teamLeader: 'Jeremy Green', phone: '0457 050 793', email: 'jeremy.green@dpi.qld.gov.au', altLeader: 'Claire Taylor', altPhone: '0407 349 737', altEmail: 'claire.taylor@dpi.qld.gov.au', area: 'Rob Bielefeld; Roanne Camilleri', areaCoordinator: 'Rob Bielefeld; Roanne Camilleri', areaCoordinatorEmail: 'Rob.Bielefeld@dpi.qld.gov.au; Roanne.Camilleri@dpi.qld.gov.au', type: '', depotLocation: 'Laidley', status: 'active', battery: 76 },
    { teamNumber: '26', teamLeader: 'Darryl Moustoukas', phone: '0461 303 430', email: 'Darryl.Moustoukas@dpi.qld.gov.au', altLeader: 'Dennis Warner', altPhone: '0436 699 917', altEmail: 'dennis.warner@dpi.qld.gov.au', area: 'Tanille Rachinger', areaCoordinator: 'Tanille Rachinger', areaCoordinatorEmail: 'tanille.rachinger@dpi.qld.gov.au', type: '', depotLocation: 'Gold Coast', status: 'active', battery: 79 },
    { teamNumber: '55', teamLeader: 'Grace Prince', phone: '0472 719 630', email: 'grace.prince@dpi.qld.gov.au', altLeader: 'Matthew Downes', altPhone: '0474 817 373', altEmail: 'matthew.downes@dpi.qld.gov.au', area: 'Sean Melton', areaCoordinator: 'Sean Melton', areaCoordinatorEmail: 'sean.melton@dpi.qld.gov.au', type: '', depotLocation: 'Caboolture', status: 'active', battery: 71 },
    { teamNumber: '7', teamLeader: 'Warren Plumber', phone: '0460 009 114', email: 'warren.plumber@dpi.qld.gov.au', altLeader: 'Harry Duffy', altPhone: '0499 978 171', altEmail: 'harry.duffy@dpi.qld.gov.au', area: 'Jamie', areaCoordinator: 'Chris Acworth', areaCoordinatorEmail: 'chris.acworth@dpi.qld.gov.au', type: '', depotLocation: 'Berrinba/Wacol', status: 'active', battery: 85 },
    { teamNumber: '56', teamLeader: 'Isabella Armstrong', phone: '0459 652 226', email: 'isabella.armstrong@dpi.qld.gov.au', altLeader: 'Eric Clatworthy', altPhone: '0456 157 345', altEmail: 'eric.clatworthy@dpi.qld.gov.au', area: 'Andrew Wratt', areaCoordinator: 'Andrew Wratt', areaCoordinatorEmail: 'andrew.wratt@dpi.qld.gov.au', type: '', depotLocation: 'Caboolture', status: 'active', battery: 68 },
    { teamNumber: '20', teamLeader: 'Jason Bell (acting)', phone: '0459 864 810', email: 'jason.bell@dpi.qld.gov.au', altLeader: 'Joseph Formosa', altPhone: '0460 015 241', altEmail: 'joseph.formosa@dpi.qld.gov.au', area: 'Jamie', areaCoordinator: 'Chris Acworth', areaCoordinatorEmail: 'chris.acworth@dpi.qld.gov.au', type: '', depotLocation: 'Berrinba/Wacol', status: 'active', battery: 77 },
    { teamNumber: '45', teamLeader: 'Solange Straetmans', phone: '0458 443 039', email: 'solange.straetmans@dpi.qld.gov.au', altLeader: 'Nikki Rakabuta', altPhone: '0497 017 564', altEmail: 'nikki.rakabuta@dpi.qld.gov.au', area: 'Andrew (Drew) Wratt', areaCoordinator: 'Andrew (Drew) Wratt', areaCoordinatorEmail: 'andrew.wratt@dpi.qld.gov.au', type: '', depotLocation: 'Caboolture', status: 'active', battery: 70 },
    { teamNumber: '29', teamLeader: 'Lyle Thompson', phone: '0418 667 195', email: 'lyle.thompson@dpi.qld.gov.au', altLeader: 'Brendan Charlton', altPhone: '0436 680 894', altEmail: 'brendan.charlton@dpi.qld.gov.au', area: 'Tanille Rachinger', areaCoordinator: 'Tanille Rachinger', areaCoordinatorEmail: 'tanille.rachinger@dpi.qld.gov.au', type: '', depotLocation: 'Gold Coast', status: 'active', battery: 74 },
    { teamNumber: '21', teamLeader: 'John Thalhammer', phone: '0461 280 038', email: 'john.thalhammer@dpi.qld.gov.au', altLeader: 'Craig Firmstone', altPhone: '0419 692 976', altEmail: 'craig.firmstone@dpi.qld.gov.au', area: 'Jade Dean', areaCoordinator: 'Jade Dean', areaCoordinatorEmail: 'jade.dean@dpi.qld.gov.au', type: '', depotLocation: 'Gold Coast', status: 'active', battery: 81 },
    { teamNumber: '10-A', teamLeader: 'Ayden Championeys', phone: '0459 731 767', email: 'ayden.championeys@dpi.qld.gov.au', altLeader: 'Kai Sipple-Spoeckman', altPhone: '0455 028 894', altEmail: 'kai.sipplespoeckman@dpi.qld.gov.au', area: 'Jarred', areaCoordinator: 'Michelle', areaCoordinatorEmail: 'michelle@dpi.qld.gov.au', type: 'K9', depotLocation: 'Berrinba/Wacol', status: 'active', battery: 83 },
    { teamNumber: '17', teamLeader: 'Fiona Thompson', phone: '0409 059 593', email: 'fiona.thompson@dpi.qld.gov.au', altLeader: 'Broden Duffey', altPhone: '0427 970 230', altEmail: 'broden.duffey@dpi.qld.gov.au', area: 'Jamie', areaCoordinator: 'Chris Acworth', areaCoordinatorEmail: 'chris.acworth@dpi.qld.gov.au', type: '', depotLocation: 'Berrinba/Wacol', status: 'active', battery: 78 },
    { teamNumber: '10', teamLeader: 'Jarred Nielsenhhh', phone: '0436 680 246', email: 'jarred.nielsen@dpi.qld.gov.au', altLeader: 'Simon Johnson', altPhone: '0436 668 950', altEmail: 'simon.johnson@dpi.qld.gov.au', area: 'Jarred', areaCoordinator: 'Michellehhbbh', areaCoordinatorEmail: 'michelle@dpi.qld.gov.au', type: 'K9', depotLocation: 'Berrinba/Wacol', status: 'active', battery: 86 },
    { teamNumber: '57', teamLeader: 'Vacant', phone: '0407 763 384', email: 'Sean.Melton@dpi.qld.gov.au', altLeader: 'Amanda Steutel', altPhone: '0436 668 591', altEmail: 'amanda.steutel@dpi.qld.gov.au', area: 'Sean Melton', areaCoordinator: 'Sean Melton', areaCoordinatorEmail: 'Sean.Melton@dpi.qld.gov.au', type: '', depotLocation: 'Caboolture', status: 'active', battery: 69 },
    { teamNumber: '47', teamLeader: 'Charlotte Lear', phone: '0458 776 360', email: 'charlotte.lear@dpi.qld.gov.au', altLeader: 'Richard Grant', altPhone: '0475 802 331', altEmail: 'richard.grant@dpi.qld.gov.au', area: 'Sean Melton', areaCoordinator: 'Sean Melton', areaCoordinatorEmail: 'sean.melton@dpi.qld.gov.au', type: '', depotLocation: 'Caboolture', status: 'active', battery: 72 },
    { teamNumber: 'FAST-7', teamLeader: 'Sonia Cahill', phone: '0476 868 524', email: 'sonia.cahill@dpi.qld.gov.au', altLeader: '', altPhone: '', altEmail: '', area: 'Fast Aerial', areaCoordinator: 'William Taylor', areaCoordinatorEmail: 'william.taylor@dpi.qld.gov.au', type: 'Fast Aerial', depotLocation: 'Fast Aerial Operations', status: 'active', battery: 90 },
    { teamNumber: '15', teamLeader: 'Lada Stasch', phone: '0492 321 025', email: 'lada.stasch@dpi.qld.gov.au', altLeader: 'Brooke Smith', altPhone: '0436 660 005', altEmail: 'brooke.smith@dpi.qld.gov.au', area: 'Sam MacFarlane', areaCoordinator: 'Sam MacFarlane', areaCoordinatorEmail: 'sam.macfarlane@dpi.qld.gov.au', type: '', depotLocation: 'Gold Coast', status: 'active', battery: 75 },
    { teamNumber: '42', teamLeader: 'Grayson Churchill', phone: '0491 381 561', email: 'grayson.churchill@dpi.qld.gov.au', altLeader: 'Kate Single', altPhone: '0422 116 099', altEmail: 'Non-DPI staff member', area: 'Carolina Hengler', areaCoordinator: 'Carolina Hengler', areaCoordinatorEmail: 'Carolina.Hengler@dpi.qld.gov.au', type: '', depotLocation: 'Caboolture', status: 'active', battery: 73 },
    { teamNumber: '43', teamLeader: 'David Fitzpatrick', phone: '0436 809 633', email: 'david.fitzpatrick@dpi.qld.gov.au', altLeader: 'Samuel Barnett', altPhone: '0448 393 397', altEmail: 'samuel.barnett@dpi.qld.gov.au', area: 'Carolina Hengler', areaCoordinator: 'Carolina Hengler', areaCoordinatorEmail: 'carolina.hengler@dpi.qld.gov.au', type: '', depotLocation: 'Caboolture', status: 'active', battery: 76 },
    { teamNumber: '14', teamLeader: 'Shane Collier', phone: '0408 427 965', email: 'shane.collier@dpi.qld.gov.au', altLeader: 'Jamie Scott', altPhone: '0498 857 056', altEmail: 'jamie.scott@dpi.qld.gov.au', area: 'Sam MacFarlane', areaCoordinator: 'Sam MacFarlane', areaCoordinatorEmail: 'sam.macfarlane@dpi.qld.gov.au', type: '', depotLocation: 'Gold Coast', status: 'active', battery: 79 },
    { teamNumber: 'DOGS', teamLeader: 'Jordan Christinson', phone: '0422 116 138', email: 'jordan.christinson@dpi.qld.gov.au', altLeader: '', altPhone: '', altEmail: '', area: 'Jarred', areaCoordinator: 'Michelle', areaCoordinatorEmail: 'michelle@dpi.qld.gov.au', type: 'K9', depotLocation: 'Berrinba/Wacol', status: 'active', battery: 82 },
    { teamNumber: 'AERIAL-4', teamLeader: 'Troy Butterfield', phone: '0476 817 673', email: 'troy.butterfield@dpi.qld.gov.au', altLeader: '', altPhone: '', altEmail: '', area: 'Aerial', areaCoordinator: 'Mikhala Barford', areaCoordinatorEmail: 'mikhala.barford@dpi.qld.gov.au', type: 'Aerial', depotLocation: 'Aerial Operations', status: 'active', battery: 87 }
];

export const DataStore = {
    query: async (model, predicate) => {
        // Simulate query logic
        if (model.name === 'AppointmentSlot') {
            return slots;
        }
        if (model.name === 'FieldTeamData') {
            return teams;
        }
        return [];
    },
    save: async (item) => {
        console.log("💾 DataStore Save:", item);
        // Simulate "save or update"
        const existingIndex = slots.findIndex(s => s.time === item.time);
        if (existingIndex >= 0) {
            slots[existingIndex] = item;
        } else {
            slots.push(item);
        }
        return item;
    },
    observe: () => {
        return { subscribe: () => ({ unsubscribe: () => {} }) };
    }
};
